apiVersion: v1
kind: PersistentVolume
metadata:
  name: asterisk-pvs
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt/data/asterisk"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: asterisk-pvsc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi