apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: a2billing-ingress
spec:
  rules:
  - host: cluster
    http:
      paths:
      - pathType: Prefix
        path: {{ .Values.webCustomer.ingressPath }}
        backend:
          service:
            name: web-customer
            port:
              number: 80
      - pathType: Prefix
        path: {{ .Values.webAdmin.ingressPath }}
        backend:
          service:
            name: web-admin
            port:
              number: 80
      - pathType: Prefix
        path: /
        backend:
          service:
            name: sip-server
            port:
              number: 5060