Version: networking.k8s.io/v1
kind: Ingress
metadata:
  name: a2billing
spec:
  rules:
  - host: cluster
    http:
      paths:
      - pathType: Prefix
        path: /customer
        backend:
          service:
            name: web-customer
            port:
              number: 80
      - pathType: Prefix
        path: /admin
        backend:
          service:
            name: web-admin
            port:
              number: 80
      - pathType: Prefix
        path: /
        backend:
          service:
            name: sip-server
            port:
              number: 5060
