apiVersion: v1
kind: Service
metadata:
  name: web-customer
spec:
  selector:
    app: web-customer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web-admin
spec:
  selector:
    app: web-admin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: sip-server
spec:
  selector:
    app: sip-server
  ports:
    - protocol: TCP
      port: 5060
      targetPort: 5060
      name: sip-tcp
    - protocol: UDP
      port: 5060
      targetPort: 5060
      name: sip-udp

