apiVersion: apps/v1
kind: Deployment
metadata:
  name: sip-server
  labels:
    app: sip-server
spec:
  selector:
    matchLabels:
      app: sip-server
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: sip-server
    spec:
      containers:
        - name: asterisk
          image: asterisk
          ports:
            - containerPort: 5060
              protocol: UDP
            - containerPort: 5060
              protocol: TCP
