apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sip-server
  labels:
    app: sip-server
spec:
  selector:
    matchLabels:
      app: sip-server
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: sip-server
    spec:
      containers:
        - name: asterisk
          image: {{ .Values.asterisk.image }}
          envFrom:
            - configMapRef:
                name: asterisk-configmap
            - configMapRef:
                name: mysql-configmap
          env:
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD
          ports:
            - containerPort: 5060
              protocol: UDP
            - containerPort: 5060
              protocol: TCP
      #     volumeMounts:
      #       - name: asterisk-config
      #         mountPath: /etc/asterisk
      #       - name: astrisk-data
      #         mountPath: /var/lib/asterisk
      #       - name: astrisk-data-spool
      #         mountPath: /var/spool/asterisk
      # volumes:
      # - name: asterisk-config
      #   persistentVolumeClaim:
      #     claimName: asterisk-pvsc
      # - name: astrisk-data
      #   persistentVolumeClaim:
      #     claimName: asterisk-pvsc
      # - name: astrisk-data-spool
      #   persistentVolumeClaim:
      #     claimName: asterisk-pvsc