apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-customer
  labels:
    app: web-customer
spec:
  selector:
    matchLabels:
      app: web-customer
  replicas: { { .Values.web-customer.replicaCount } }
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web-customer
    spec:
      containers:
        - name: web-customer
          image: {{ .Values.web-customer.image }}
          ports:
            - containerPort: 80
          env:
            - name: MYSQL_HOST
              valueFrom:
                configMapKeyRef:
                  name: mysql-configmap
                  key: MYSQL_HOST
            - name: MYSQL_PORT
              valueFrom:
                configMapKeyRef:
                  name: mysql-configmap
                  key: MYSQL_PORT
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: mysql-configmap
                  key: MYSQL_DATABASE
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD
