apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web-customer
  labels:
    app: web-customer
spec:
  selector:
    matchLabels:
      app: web-customer
  replicas: {{ .Values.webCustomer.replicaCount }}
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web-customer
    spec:
      containers:
        - name: web-customer
          image: {{ .Values.webCustomer.image }}
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: mysql-configmap
          env:
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD
