apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web-admin
  labels:
    app: web-admin
spec:
  selector:
    matchLabels:
      app: web-admin
  replicas: {{ .Values.webAdmin.replicaCount }}
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web-admin
    spec:
      containers:
        - name: web-admin
          image: {{ .Values.webAdmin.image }}
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: mysql-configmap
          env:
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD
